version: 2

updates:
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - "fredclausen"
      - "mikenye"
      - "kx1t"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "fredclausen"
      - "mikenye"
